# Save the current 3D map to a file

# Filename of the map file
string map_filename
# File format [0: PLY, 1: PLY_BIN, 2: OBJ]
uint8 file_format
---
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
